### ISSUE TITLE
Fuzzer can generate keywords as identifiers

### ISSUE THREAD

**Issue by bitowl** [comprakt/comprakt-fuzz#1]
In the grammar, IDENT can be any kind of characters, so the fuzzer generated this:
```
public if bSO(c P4ZIcme)  {
```

Which resulted in the tokens:
```
public
identifier if
identifier bSO
(
identifier c
identifier P4ZIcme
)
{ 
```

As `if` is a keyword in MiniJava the Lexer should not parse it as an identifier.

Same could happen with other keywords that have ten characters or less.

**Comment by flip1995** [comment]
Thanks for pointing that out! I don't think this can be fixed here, but I can hack this in my fork of the gramfuzz lib.

**Comment by flip1995** [comment]
This is fixed with https://github.com/flip1995/gramfuzz/commit/1470529397def3ce8b7f561f48d1a616f245a506

Feel free to reopen if this happens again!
